{
	"version": 1775860980,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/platform-sheet0.png",
		"images/startscreenbg.png",
		"images/enemyhillary-sheet0.png",
		"images/enemytrump-sheet0.png",
		"images/ballotcollectable-sheet0.png",
		"images/gamebg.png",
		"images/highscorebutton-sheet0.png",
		"images/startbutton-sheet0.png",
		"images/imagearrowkeys-sheet0.png",
		"images/scorebackground-sheet0.png",
		"images/instructionsbutton-sheet0.png",
		"images/creditsbutton-sheet0.png",
		"images/homebutton-sheet0.png",
		"images/gametitleimage-sheet0.png",
		"images/redlaser-sheet0.png",
		"images/newhighscore-sheet0.png",
		"images/particles.png",
		"images/replay-sheet0.png",
		"media/game-menu-002.ogg",
		"media/game-menu_v001.ogg",
		"media/life-lost-game-over.ogg",
		"media/pterodactyl_screech-mike_koenig-1344719300.ogg",
		"media/laser_shoot42.ogg",
		"media/hillary clinton laughs (online-video-cutter.com).ogg",
		"media/bald eagle screaming-222.ogg",
		"media/donald trump hello, bingbingbong.ogg",
		"media/game-background-1.ogg",
		"media/game-background-2.ogg",
		"media/game-background-3.ogg",
		"media/sousa_the_stars_and_stripes_forever_-_-the_preside.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}